package scalacucumberplaywright

class Selectors {

  val userName = "#user-name"
  val password = "#password"
  val loginButton = "#login-button"
  val homepageTitle = ".app_logo"
  val errorMessage = ".error-message-container.error h3"
  val loginpageTitle = ".login_logo"
  val menu = "#react-burger-menu-btn"
  val logoutButton = "#logout_sidebar_link"
  val productBackpack = "button[name*=sauce-labs-backpack]"
  val productBikelight = "button[name*=sauce-labs-bike-light]"
  val productTshirt = "button[name*=sauce-labs-bolt-t-shirt]"
  val productJacket = "button[name*=sauce-labs-fleece-jacket]"
  val productOnesie = "button[name*=sauce-labs-onesie]"
  val productTshirtRed = "button[name*=allthethings]"
  val cart = ".shopping_cart_link"
  val checkout = "#checkout"
  val firstName = "#first-name"
  val lastName = "#last-name"
  val zipCode = "#postal-code"
  val continueButton = "#continue"
  val finishButton = "#finish"
  val checkoutBanner = ".complete-header"
  val taxCalculated = ".summary_tax_label"
  val subtotal = ".summary_subtotal_label"
  val fullTotal = "div[class*=summary_total_label]"
  val priceList = ".inventory_item_price"
  val itemNumberInCart = ".shopping_cart_badge"
  val productSort = ".product_sort_container"
  val productList = ".inventory_item_name"
  val footer = ".footer"
  val footerTwitter = ".social_twitter a"
  val footerFacebook = ".social_facebook a"
  val footerLinkedin = ".social_linkedin a"

}
